### ISSUE TITLE
More of a Question

### ISSUE THREAD

**Issue by SSutherland94** [zizi4n5/homebridge-switchbot-for-mac#1]
I see in the ReadMe, that only Switchbot woHand devices are supported. I'm pretty new to this, so what exactly does woHand mean? I want to make sure this is actually going to work before I go and buy a Switchbot. Thanks in advance!

**Comment by zizi4n5** [comment]
@SSutherland94 

Sorry. I just noticed this Issue.
The "Switchbot woHand devices" refers to the following products.

* [SwitchBot(Button Pressor)](https://www.switch-bot.com/bot)

Later, I'll update the readme as well.
Thank you for contacting me.
