### ISSUE TITLE
Configuration of more than 1 switch fails / on-off mode

### ISSUE THREAD

**Issue by padman74** [zizi4n5/homebridge-switchbot-for-mac#20]
Hello.

I configured two switchbots by defining two accessories in config file having different names. Both accessories appear as switches in Homekit. But in Homekit the second one shows randomly on and off without any reason. When I configure only 1 switch it shows constantly on. What makes the switch showing on/off?

Further I don't understand why the switch needs to be on if it should be a stateless button. I would expect the opposite. 

Regards
padman

**Comment by zizi4n5** [comment]
Describe the contents of the Config for the two SwitchBots you have set up for Homebridge.

e.g.
```
{
    "accessories": [
        {
            "accessory": "SwitchBot-For-Mac",
            "name": "Switch",
            "delay": 5000,
            "retries": 3,
            "macAddress": "01:23:45:67:89:AB",
            "ping": {
                "ipAddress": "127.0.0.1",
                "interval": 2000,
                "retries": 1,
                "timeout": 1000
            }
        }
    ]
}
```

**Comment by padman74** [comment]
{
            "accessory": "SwitchBot-For-Mac",
            "name": "Bedroom",
            "delay": 5000,
            "retries": 3,
            "macAddress": "xx:xx:xx:xx:xx:xx",
            "ping": {
                "ipAddress": "127.0.0.1",
                "interval": 2000,
                "retries": 1,
                "timeout": 1000
            }
	},
	{
            "accessory": "SwitchBot-For-Mac",
            "name": "Kitchen",
            "delay": 5000,
            "retries": 3,
            "macAddress": "yy:yy:yy:yy:yy:yy",
            "ping": {
                "ipAddress": "127.0.0.1",
                "interval": 2000,
                "retries": 1,
                "timeout": 1000
            } 
	},

**Comment by zizi4n5** [comment]
The ping option is only available if you can use ping to determine whether a device is on or off.
Set the ipAddress of the target device, not "127.0.0.1".

Otherwise, remove the ping option.

**Comment by padman74** [comment]
got it, thank you!
