### ISSUE TITLE
Plugin Does Not Work Following Reboot

### ISSUE THREAD

**Issue by SSutherland94** [zizi4n5/homebridge-switchbot-for-mac#3]
I have my Mac reboot automatically every night. However, it seems that this plugin breaks when my Mac powers on until I restart Homebridge again after. This is the excerpt from the log. Hope someone can help with this!
`[37m[5/31/2020, 6:10:49 AM] [39mHomebridge is running on port 51745.
(node:467) UnhandledPromiseRejectionWarning: Error: send ENETUNREACH 255.255.255.255:987
    at doSend (dgram.js:697:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:296:12)
    at afterDns (dgram.js:643:5)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
(node:467) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:467) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:467) UnhandledPromiseRejectionWarning: Error: Failed to initialize the Noble object: unknown
    at Noble.<anonymous> (/usr/local/lib/node_modules/homebridge-switchbot-for-mac/node_modules/node-switchbot/lib/switchbot.js:172:23)
    at Object.onceWrapper (events.js:417:26)
    at Noble.emit (events.js:322:22)
    at Noble.onStateChange (/usr/local/lib/node_modules/homebridge-switchbot-for-mac/node_modules/@abandonware/noble/lib/noble.js:87:8)
    at NobleMac.emit (events.js:310:20)
(node:467) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:467) UnhandledPromiseRejectionWarning: Error: Failed to initialize the Noble object: unknown
    at Noble.<anonymous> (/usr/local/lib/node_modules/homebridge-switchbot-for-mac/node_modules/node-switchbot/lib/switchbot.js:172:23)
    at Object.onceWrapper (events.js:417:26)
    at Noble.emit (events.js:322:22)
    at Noble.onStateChange (/usr/local/lib/node_modules/homebridge-switchbot-for-mac/node_modules/@abandonware/noble/lib/noble.js:87:8)
    at NobleMac.emit (events.js:310:20)
(node:467) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
[0;37m[5/31/2020, 6:10:49 AM] [0m[0;36m[Config][0m [0;33mHomebridge Config UI X v4.21.0 is listening on :: port 8581[0m
(node:467) UnhandledPromiseRejectionWarning: Error: send ENETUNREACH 255.255.255.255:987
    at doSend (dgram.js:697:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:296:12)
    at afterDns (dgram.js:643:5)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
(node:467) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
[37m[5/31/2020, 6:10:51 AM] [39m[36m[Spidey PS4] [39mFound device [Spidey PS4]
[37m[5/31/2020, 6:10:51 AM] [39m[36m[Spidey PS4] [39mFinish searching accessories
[37m[5/31/2020, 7:56:07 PM] [39m[36m[Blinds] [39mTurning on...
[37m[5/31/2020, 7:56:07 PM] [39m[36m[Blinds] [39mWoHand (cf:a4:99:de:b5:88) was failed turning on
`

**Comment by zizi4n5** [comment]
If BLE initialization is not completed when Homebridge starts up, Mac and SwitchBot connection seems to be failing.

**Comment by SSutherland94** [comment]
Do you happen to know of any way I can modify that? Or is this out of our hands

**Comment by zizi4n5** [comment]
```
[5/31/2020, 6:10:49 AM] Homebridge is running on port 51745. (node:467)
  UnhandledPromiseRejectionWarning: Error: send ENETUNREACH 255.255.255.255:987
    at doSend (dgram.js:697:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:296:12) 
    at afterDns (dgram.js:643:5) 
    at processTicksAndRejections (internal/process/task_queues.js:85:21) (node:467) 

  UnhandledPromiseRejectionWarning: Unhandled promise rejection. 
                                    This error originated either by throwing inside of an async function without a catch block, 
                                    or by rejecting a promise which was not handled with .catch(). 
                                    To terminate the node process on unhandled promise rejection, 
                                    use the CLI flag --unhandled-rejections=strict(see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). 
                                    (rejection id: 1) (node:467) 

  [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. 
                                In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. (node:467) 

  UnhandledPromiseRejectionWarning: Error: Failed to initialize the Noble object: unknown at Noble.<anonymous> (/usr/local/lib/node_modules/homebridge-switchbot-for-mac/node_modules/node-switchbot/lib/switchbot.js:172:23) 
    at Object.onceWrapper (events.js:417:26) 
    at Noble.emit (events.js:322:22) 
    at Noble.onStateChange (/usr/local/lib/node_modules/homebridge-switchbot-for-mac/node_modules/@abandonware/noble/lib/noble.js:87:8) 
    at NobleMac.emit (events.js:310:20) (node:467) 

  UnhandledPromiseRejectionWarning: Unhandled promise rejection. 
                                    This error originated either by throwing inside of an async function without a catch block, 
                                    or by rejecting a promise which was not handled with .catch(). 
                                    To terminate the node process on unhandled promise rejection, 
                                    use the CLI flag--unhandled-rejections=strict(see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). 
                                    (rejection id: 2) (node:467) 
  UnhandledPromiseRejectionWarning: Error: Failed to initialize the Noble object: unknown at Noble.<anonymous> (/usr/local/lib/node_modules/homebridge-switchbot-for-mac/node_modules/node-switchbot/lib/switchbot.js:172:23) 
    at Object.onceWrapper (events.js:417:26) at Noble.emit (events.js:322:22) 
    at Noble.onStateChange (/usr/local/lib/node_modules/homebridge-switchbot-for-mac/node_modules/@abandonware/noble/lib/noble.js:87:8) 
    at NobleMac.emit (events.js:310:20) (node:467) 
  
  UnhandledPromiseRejectionWarning: Unhandled promise rejection. 
                                    This error originated either by throwing inside of an async function without a catch block, 
                                    or by rejecting a promise which was not handled with .catch(). 
                                    To terminate the node process on unhandled promise rejection, 
                                    use the CLI flag--unhandled-rejections=strict(see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). 
                                    (rejection id: 3) 

[5/31/2020, 6:10:49 AM] [Config]Homebridge Config UI X v4.21.0 is listening on :: port 8581 (node:467) 

  UnhandledPromiseRejectionWarning: Error: send ENETUNREACH 255.255.255.255:987 
    at doSend (dgram.js:697:16) 
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:296:12) 
    at afterDns (dgram.js:643:5) 
    at processTicksAndRejections (internal/process/task_queues.js:85:21) (node:467) 
 
  UnhandledPromiseRejectionWarning: Unhandled promise rejection. 
                                    This error originated either by throwing inside of an async function without a catch block, 
                                    or by rejecting a promise which was not handled with .catch(). 
                                    To terminate the node process on unhandled promise rejection, 
                                    use the CLI flag--unhandled-rejections=strict(see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4) 
                                  
[5/31/2020, 6:10:51 AM] [Spidey PS4] Found device [Spidey PS4] 
[5/31/2020, 6:10:51 AM] [Spidey PS4] Finish searching accessories 
[5/31/2020, 7:56:07 PM] [Blinds] Turning on... 
[5/31/2020, 7:56:07 PM] [Blinds] WoHand (cf:a4:99:de:b5:88) was failed turning on
```

> Error: Failed to initialize the Noble object

This error is the same error as the following Issue, so it seems to be caused by the fact that it is still running before Bluetooth initialization.

https://github.com/futomi/node-beacon-scanner/issues/1

For this reason, I'm looking into how to wait out the Bluetooth initialization process.

**Comment by SSutherland94** [comment]
Thanks for looking into this! Hope a resolution can be found eventually!

**Comment by zizi4n5** [comment]
@SSutherland94 
I added a delay option to wait for Bluetooth initialization.
Can you check if this can be worked around?
https://github.com/zizi4n5/homebridge-switchbot-for-mac#how-to-use

**Comment by SSutherland94** [comment]
Didn’t want to leave you hanging, but I’ll gladly test this out once I’m home. Should hear back from me around 8 hours from now

**Comment by zizi4n5** [comment]
Using version 0.0.12, delay is set to a value between 0 and 30,000 milliseconds. Please try.
It is possible to specify more than 30000ms, but in my tests of operation, it was not possible to start up correctly.

**Comment by zizi4n5** [comment]
If this doesn't improve the situation, I'm going to try the Bluetooth connection again when operating the Switch.

**Comment by SSutherland94** [comment]
Worked like a charm! Used delay: 5000. I can go back to nightly reboots and easy-open shades now. Thanks!

**Comment by zizi4n5** [comment]
I'm glad it worked properly!
Then this Issue is closed.
